sudo: false

dist: bionic

cache: false

# Build only master & PRs
branches:
  only:
    - master
    - /^greenkeeper/.*$/

language: node_js

node_js:
  - "10"
  - "12"

install:
  - yarn install --immutable

env:
  - WEBPACK_VERSION=4 MOCHA_VERSION=7
  - WEBPACK_VERSION=4 MOCHA_VERSION=8
  - WEBPACK_VERSION=5 MOCHA_VERSION=7
  - WEBPACK_VERSION=5 MOCHA_VERSION=8

before_script:
  - "yarn add -D webpack@$WEBPACK_VERSION"
  - "yarn add -D mocha@$MOCHA_VERSION"
  # Need to skip ts check for getAffectedModuleIds in webpack 4
  - test WEBPACK_VERSION = 4 && echo -e "// @ts-nocheck\n$(cat src/webpack/util/getAffectedModuleIds.ts)" > src/webpack/util/getAffectedModuleIds.ts

script:
  - yarn run cover

after_success:
  - bash <(curl -s https://codecov.io/bash)
